//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    
    public partial class TicketAttachment
    {
        public int ID { get; set; }
        public int TicketID { get; set; }
        public int SubmitterID { get; set; }
        public string AttachmentFilePath { get; set; }
        public string OriginalName { get; set; }
        public string Description { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }


        public TicketAttachment(int _TicketID, int _SubmitterID, string _AttachmentFilePath, string _OriginalName, string _Description)
        {
            TicketID = _TicketID;
            SubmitterID = _SubmitterID;
            AttachmentFilePath = _AttachmentFilePath;
            OriginalName = _OriginalName;
            Description = _OriginalName ?? "No Description";
        }


        public string GetUrl()
        {
            return Regex.Replace( AttachmentFilePath, @"^(.*?)(?=/App_Data/)","~");
        }
    }
}
