//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Attachments
    {
        public int ID { get; set; }
        public int TicketID { get; set; }
        public int SubmitterID { get; set; }
        public string Attachment_File_Path { get; set; }
        public string Original_Name { get; set; }
        public string Description { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
